# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: MWMxZDg3ZDlkMmE3ZmQ5MzI2OWEwOTkyNzcyMTM5MmEyZTdjOTA2MjNjMmZlZDhlMzA3YmRhNTFkY2VmNTFkZGZlZDI2YWVlM2ZkNjA3MWZkYzE0MmRlNjBmMzA4YTFmOGQ5ODg1NDg0YTMzYmQ4ZTNmNWE5MTc0NGRkZmM2ZTA=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
