# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: MDBhZDIyMWQ5M2ZmYWI1NjQ1MTAwNDk3MDFmYjRkOTAxNzg4MWIxMDNiZmJiZGJhZjMzNzU2NmI4YTQzZDRjOGFmYTk4NTJiM2Q2NjY5YWM5ZmNhYThjOGJmZjc3MzkzZDJkMjljZTFjMTAyNWU5OTZlZGRlYjY3NmRjNDNkMzY=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@localhost:8761/eureka/
